app = 'staff-bot'
primary_region = 'iad'
kill_signal = 'SIGTERM'

[build]

[env]
  DATABASE_PATH = '/app/data/staff_bot.db'
  PHX_HOST = 'staff-bot.fly.dev'
  PORT = '8080'

[experimental]
  auto_rollback = true

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['http', 'tls']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '1s'
    method = 'get'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = 'staff_bot_data'
  destination = '/app/data'
